// ============================================================
// LinkVerse Frontend Constants
// All shared constants, enums, and configuration objects
// ============================================================

// ---- Platform options for link creation dropdown ----
export const PLATFORM_OPTIONS = [
  { value: 'custom', label: 'Custom URL', icon: 'FiLink', color: '#6366f1' },
  { value: 'instagram_post', label: 'Instagram Post', icon: 'FaInstagram', color: '#E4405F' },
  { value: 'instagram_reel', label: 'Instagram Reel', icon: 'FaInstagram', color: '#E4405F' },
  { value: 'youtube_video', label: 'YouTube Video', icon: 'FaYoutube', color: '#FF0000' },
  { value: 'youtube_channel', label: 'YouTube Channel', icon: 'FaYoutube', color: '#FF0000' },
  { value: 'blog', label: 'Blog Post', icon: 'FaBlog', color: '#F97316' },
  { value: 'website', label: 'Website', icon: 'FiGlobe', color: '#3B82F6' },
  { value: 'shop', label: 'Shop / Store', icon: 'FiShoppingBag', color: '#10B981' },
  { value: 'whatsapp', label: 'WhatsApp', icon: 'FaWhatsapp', color: '#25D366' },
  { value: 'telegram', label: 'Telegram', icon: 'FaTelegram', color: '#0088cc' },
  { value: 'discord', label: 'Discord', icon: 'FaDiscord', color: '#5865F2' },
  { value: 'spotify', label: 'Spotify', icon: 'FaSpotify', color: '#1DB954' },
  { value: 'apple_music', label: 'Apple Music', icon: 'FaApple', color: '#FA243C' },
  { value: 'jiosaavn', label: 'JioSaavn', icon: 'FaMusic', color: '#2BC5B4' },
  { value: 'gaana', label: 'Gaana', icon: 'FaMusic', color: '#E72C30' },
  { value: 'wynk', label: 'Wynk Music', icon: 'FaMusic', color: '#1D1D2C' },
  { value: 'moj', label: 'Moj', icon: 'FaVideo', color: '#F44336' },
  { value: 'sharechat', label: 'ShareChat', icon: 'FaComments', color: '#FFD54F' },
  { value: 'josh', label: 'Josh', icon: 'FaPlay', color: '#FF5722' },
  { value: 'chingari', label: 'Chingari', icon: 'FaFire', color: '#FF9800' },
  { value: 'roposo', label: 'Roposo', icon: 'FaCamera', color: '#E91E63' },
  { value: 'amazon_affiliate', label: 'Amazon Affiliate', icon: 'FaAmazon', color: '#FF9900' },
  { value: 'flipkart_affiliate', label: 'Flipkart Affiliate', icon: 'FiShoppingCart', color: '#2874F0' },
  { value: 'meesho', label: 'Meesho', icon: 'FiShoppingBag', color: '#E91E63' },
  { value: 'razorpay', label: 'Razorpay Payment Link', icon: 'FiCreditCard', color: '#0066FF' },
  { value: 'google_form', label: 'Google Form', icon: 'FiFileText', color: '#673AB7' },
  { value: 'topmate', label: 'Topmate', icon: 'FiCalendar', color: '#FF6B6B' },
  { value: 'calendly', label: 'Calendly', icon: 'FiCalendar', color: '#006BFF' },
  { value: 'buymeacoffee', label: 'Buy Me a Coffee', icon: 'FiCoffee', color: '#FFDD00' },
  { value: 'kofi', label: 'Ko-fi', icon: 'FiCoffee', color: '#FF5E5B' },
  { value: 'gumroad', label: 'Gumroad', icon: 'FiShoppingCart', color: '#FF90E8' },
  { value: 'notion', label: 'Notion', icon: 'FiFile', color: '#000000' },
  { value: 'linktree', label: 'Linktree', icon: 'FiLink', color: '#43E660' },
  { value: 'other', label: 'Other', icon: 'FiLink2', color: '#6B7280' },
];

// ---- Social platforms grouped by category ----
export const SOCIAL_PLATFORMS = {
  indian: [
    { key: 'moj', label: 'Moj', icon: 'FaVideo', placeholder: 'Your Moj profile URL', prefix: 'https://mojapp.in/@' },
    { key: 'sharechat', label: 'ShareChat', icon: 'FaComments', placeholder: 'Your ShareChat profile URL', prefix: '' },
    { key: 'joshapp', label: 'Josh', icon: 'FaPlay', placeholder: 'Your Josh profile URL', prefix: '' },
    { key: 'chingari', label: 'Chingari', icon: 'FaFire', placeholder: 'Your Chingari profile URL', prefix: '' },
    { key: 'roposo', label: 'Roposo', icon: 'FaCamera', placeholder: 'Your Roposo profile URL', prefix: '' },
    { key: 'koo', label: 'Koo', icon: 'FaComment', placeholder: 'Your Koo profile URL', prefix: '' },
  ],
  global: [
    { key: 'instagram', label: 'Instagram', icon: 'FaInstagram', placeholder: 'username (without @)', prefix: 'https://instagram.com/' },
    { key: 'youtube', label: 'YouTube', icon: 'FaYoutube', placeholder: 'channel URL or @handle', prefix: 'https://youtube.com/@' },
    { key: 'twitter', label: 'Twitter / X', icon: 'FaTwitter', placeholder: 'username (without @)', prefix: 'https://twitter.com/' },
    { key: 'facebook', label: 'Facebook', icon: 'FaFacebook', placeholder: 'profile or page URL', prefix: 'https://facebook.com/' },
    { key: 'linkedin', label: 'LinkedIn', icon: 'FaLinkedin', placeholder: 'profile URL or username', prefix: 'https://linkedin.com/in/' },
    { key: 'snapchat', label: 'Snapchat', icon: 'FaSnapchat', placeholder: 'username', prefix: 'https://snapchat.com/add/' },
    { key: 'pinterest', label: 'Pinterest', icon: 'FaPinterest', placeholder: 'username', prefix: 'https://pinterest.com/' },
    { key: 'threads', label: 'Threads', icon: 'FaAtlas', placeholder: 'username (without @)', prefix: 'https://threads.net/@' },
    { key: 'reddit', label: 'Reddit', icon: 'FaReddit', placeholder: 'username (without u/)', prefix: 'https://reddit.com/user/' },
  ],
  messaging: [
    { key: 'whatsapp', label: 'WhatsApp', icon: 'FaWhatsapp', placeholder: '10-digit mobile number', prefix: '+91' },
    { key: 'telegram', label: 'Telegram', icon: 'FaTelegram', placeholder: 'username', prefix: 'https://t.me/' },
    { key: 'discord', label: 'Discord', icon: 'FaDiscord', placeholder: 'invite link or server URL', prefix: '' },
  ],
  music: [
    { key: 'spotify', label: 'Spotify', icon: 'FaSpotify', placeholder: 'profile or artist URL', prefix: '' },
    { key: 'applemusic', label: 'Apple Music', icon: 'FaApple', placeholder: 'artist URL', prefix: '' },
    { key: 'jiosaavn', label: 'JioSaavn', icon: 'FaMusic', placeholder: 'artist URL', prefix: '' },
    { key: 'gaana', label: 'Gaana', icon: 'FaMusic', placeholder: 'artist URL', prefix: '' },
    { key: 'wynkmusic', label: 'Wynk Music', icon: 'FaMusic', placeholder: 'artist URL', prefix: '' },
    { key: 'hungama', label: 'Hungama', icon: 'FaMusic', placeholder: 'profile URL', prefix: '' },
  ],
  professional: [
    { key: 'github', label: 'GitHub', icon: 'FaGithub', placeholder: 'username', prefix: 'https://github.com/' },
    { key: 'dribbble', label: 'Dribbble', icon: 'FaDribbble', placeholder: 'username', prefix: 'https://dribbble.com/' },
    { key: 'behance', label: 'Behance', icon: 'FaBehance', placeholder: 'username', prefix: 'https://behance.net/' },
    { key: 'medium', label: 'Medium', icon: 'FaMedium', placeholder: 'username (without @)', prefix: 'https://medium.com/@' },
    { key: 'substack', label: 'Substack', icon: 'FiFileText', placeholder: 'your-newsletter.substack.com', prefix: '' },
    { key: 'quora', label: 'Quora', icon: 'FaQuora', placeholder: 'profile URL', prefix: 'https://quora.com/profile/' },
  ],
};

// ---- All Indian states and union territories ----
export const INDIAN_STATES = [
  { value: 'Andhra Pradesh', label: 'Andhra Pradesh' },
  { value: 'Arunachal Pradesh', label: 'Arunachal Pradesh' },
  { value: 'Assam', label: 'Assam' },
  { value: 'Bihar', label: 'Bihar' },
  { value: 'Chhattisgarh', label: 'Chhattisgarh' },
  { value: 'Goa', label: 'Goa' },
  { value: 'Gujarat', label: 'Gujarat' },
  { value: 'Haryana', label: 'Haryana' },
  { value: 'Himachal Pradesh', label: 'Himachal Pradesh' },
  { value: 'Jharkhand', label: 'Jharkhand' },
  { value: 'Karnataka', label: 'Karnataka' },
  { value: 'Kerala', label: 'Kerala' },
  { value: 'Madhya Pradesh', label: 'Madhya Pradesh' },
  { value: 'Maharashtra', label: 'Maharashtra' },
  { value: 'Manipur', label: 'Manipur' },
  { value: 'Meghalaya', label: 'Meghalaya' },
  { value: 'Mizoram', label: 'Mizoram' },
  { value: 'Nagaland', label: 'Nagaland' },
  { value: 'Odisha', label: 'Odisha' },
  { value: 'Punjab', label: 'Punjab' },
  { value: 'Rajasthan', label: 'Rajasthan' },
  { value: 'Sikkim', label: 'Sikkim' },
  { value: 'Tamil Nadu', label: 'Tamil Nadu' },
  { value: 'Telangana', label: 'Telangana' },
  { value: 'Tripura', label: 'Tripura' },
  { value: 'Uttar Pradesh', label: 'Uttar Pradesh' },
  { value: 'Uttarakhand', label: 'Uttarakhand' },
  { value: 'West Bengal', label: 'West Bengal' },
  { value: 'Andaman & Nicobar Islands', label: 'Andaman & Nicobar Islands' },
  { value: 'Chandigarh', label: 'Chandigarh' },
  { value: 'Dadra & Nagar Haveli and Daman & Diu', label: 'Dadra & Nagar Haveli and Daman & Diu' },
  { value: 'Delhi', label: 'Delhi' },
  { value: 'Jammu & Kashmir', label: 'Jammu & Kashmir' },
  { value: 'Ladakh', label: 'Ladakh' },
  { value: 'Lakshadweep', label: 'Lakshadweep' },
  { value: 'Puducherry', label: 'Puducherry' },
];

// ---- Creator categories ----
export const CATEGORIES = [
  'Fashion', 'Beauty', 'Tech', 'Gaming', 'Food',
  'Travel', 'Fitness', 'Education', 'Finance', 'Comedy',
  'Music', 'Art', 'Photography', 'Lifestyle', 'Motivation',
  'News', 'Sports', 'Vlogs', 'Reviews', 'Other',
];

// ---- Category emoji mapping ----
export const CATEGORY_EMOJIS: Record<string, string> = {
  Fashion: '👗',
  Beauty: '💄',
  Tech: '💻',
  Gaming: '🎮',
  Food: '🍕',
  Travel: '✈️',
  Fitness: '💪',
  Education: '📚',
  Finance: '💰',
  Comedy: '😂',
  Music: '🎵',
  Art: '🎨',
  Photography: '📸',
  Lifestyle: '🌟',
  Motivation: '🔥',
  News: '📰',
  Sports: '⚽',
  Vlogs: '🎬',
  Reviews: '⭐',
  Other: '🔗',
};

// ---- Reserved usernames (cannot be used by users) ----
export const RESERVED_USERNAMES = [
  'admin', 'dashboard', 'login', 'signup', 'settings',
  'api', 'public', 'about', 'contact', 'pricing',
  'terms', 'privacy', 'refund', 'support', 'help',
  'billing', 'analytics', 'preview', 'explore', 'search',
  'home', 'index', 'app', 'www', 'mail', 'ftp', 'blog',
];

// ---- Font options for theme customization ----
export const FONT_OPTIONS = [
  { value: 'Inter', label: 'Inter', description: 'Clean and modern' },
  { value: 'Poppins', label: 'Poppins', description: 'Friendly and bold' },
  { value: 'Roboto', label: 'Roboto', description: 'Simple and readable' },
  { value: 'Nunito', label: 'Nunito', description: 'Soft and rounded' },
  { value: 'Outfit', label: 'Outfit', description: 'Sleek and elegant' },
];

// ---- Button style options ----
export const BUTTON_STYLES = [
  { value: 'rounded', label: 'Rounded', description: 'Softly rounded corners', cssClass: 'rounded-lg' },
  { value: 'pill', label: 'Pill', description: 'Fully rounded capsule shape', cssClass: 'rounded-full' },
  { value: 'square', label: 'Square', description: 'Sharp square corners', cssClass: 'rounded-none' },
  { value: 'outline', label: 'Outline', description: 'Transparent with border', cssClass: 'rounded-lg border-2' },
  { value: 'shadow', label: 'Shadow', description: 'Elevated with shadow', cssClass: 'rounded-lg shadow-lg' },
];

// ---- Default theme values ----
export const DEFAULT_THEME = {
  backgroundColor: '#ffffff',
  cardColor: '#f3f4f6',
  textColor: '#111827',
  buttonColor: '#6366f1',
  buttonTextColor: '#ffffff',
  fontFamily: 'Poppins',
  buttonStyle: 'pill',
  backgroundType: 'solid',
  gradientFrom: '#6366f1',
  gradientTo: '#ec4899',
  backgroundImage: '',
};

// ---- 10 Preset themes ----
export const PRESET_THEMES = [
  {
    name: 'Clean White',
    backgroundColor: '#ffffff',
    cardColor: '#f3f4f6',
    textColor: '#111827',
    buttonColor: '#6366f1',
    buttonTextColor: '#ffffff',
    fontFamily: 'Poppins',
    buttonStyle: 'pill',
    backgroundType: 'solid',
    gradientFrom: '',
    gradientTo: '',
  },
  {
    name: 'Dark Mode',
    backgroundColor: '#111827',
    cardColor: '#1f2937',
    textColor: '#f9fafb',
    buttonColor: '#06b6d4',
    buttonTextColor: '#ffffff',
    fontFamily: 'Inter',
    buttonStyle: 'rounded',
    backgroundType: 'solid',
    gradientFrom: '',
    gradientTo: '',
  },
  {
    name: 'Sunset Vibes',
    backgroundColor: '#ff8a00',
    cardColor: '#ffffff',
    textColor: '#1f2937',
    buttonColor: '#ec4899',
    buttonTextColor: '#ffffff',
    fontFamily: 'Poppins',
    buttonStyle: 'pill',
    backgroundType: 'gradient',
    gradientFrom: '#ff8a00',
    gradientTo: '#e52e71',
  },
  {
    name: 'Forest Green',
    backgroundColor: '#064e3b',
    cardColor: '#065f46',
    textColor: '#ecfdf5',
    buttonColor: '#34d399',
    buttonTextColor: '#064e3b',
    fontFamily: 'Nunito',
    buttonStyle: 'rounded',
    backgroundType: 'solid',
    gradientFrom: '',
    gradientTo: '',
  },
  {
    name: 'Royal Purple',
    backgroundColor: '#2e1065',
    cardColor: '#3b0764',
    textColor: '#f5f3ff',
    buttonColor: '#eab308',
    buttonTextColor: '#1f2937',
    fontFamily: 'Outfit',
    buttonStyle: 'shadow',
    backgroundType: 'solid',
    gradientFrom: '',
    gradientTo: '',
  },
  {
    name: 'Tricolor',
    backgroundColor: '#ff9933',
    cardColor: '#ffffff',
    textColor: '#1f2937',
    buttonColor: '#138808',
    buttonTextColor: '#ffffff',
    fontFamily: 'Poppins',
    buttonStyle: 'pill',
    backgroundType: 'gradient',
    gradientFrom: '#ff9933',
    gradientTo: '#138808',
  },
  {
    name: 'Neon Night',
    backgroundColor: '#000000',
    cardColor: '#0a0a0a',
    textColor: '#ffffff',
    buttonColor: '#f0abfc',
    buttonTextColor: '#000000',
    fontFamily: 'Roboto',
    buttonStyle: 'outline',
    backgroundType: 'solid',
    gradientFrom: '',
    gradientTo: '',
  },
  {
    name: 'Pastel Dream',
    backgroundColor: '#fce7f3',
    cardColor: '#ffffff',
    textColor: '#831843',
    buttonColor: '#f472b6',
    buttonTextColor: '#ffffff',
    fontFamily: 'Nunito',
    buttonStyle: 'pill',
    backgroundType: 'solid',
    gradientFrom: '',
    gradientTo: '',
  },
  {
    name: 'Ocean Blue',
    backgroundColor: '#1e40af',
    cardColor: '#1e3a8a',
    textColor: '#eff6ff',
    buttonColor: '#60a5fa',
    buttonTextColor: '#1e3a8a',
    fontFamily: 'Inter',
    buttonStyle: 'rounded',
    backgroundType: 'gradient',
    gradientFrom: '#1e3a8a',
    gradientTo: '#3b82f6',
  },
  {
    name: 'Minimal Gray',
    backgroundColor: '#f3f4f6',
    cardColor: '#ffffff',
    textColor: '#111827',
    buttonColor: '#374151',
    buttonTextColor: '#ffffff',
    fontFamily: 'Inter',
    buttonStyle: 'rounded',
    backgroundType: 'solid',
    gradientFrom: '',
    gradientTo: '',
  },
];

// ---- App configuration ----
export const APP_CONFIG = {
  appName: 'LinkVerse',
  tagline: 'One Link For Everything!',
  baseUrl: 'linkverse.com',
  supportEmail: 'support@linkverse.com',
  maxBio: 160,
  maxLinks: 50,
  maxLinkTitle: 80,
  maxMetaTitle: 60,
  maxMetaDescription: 160,
  maxFileSize: 5 * 1024 * 1024, // 5MB
  profilePicSize: 400,
  ogImageWidth: 1200,
  ogImageHeight: 630,
};

// ---- Subscription config ----
export const SUBSCRIPTION = {
  monthly: {
    price: 49,
    priceInPaise: 4900,
    currency: 'INR',
    period: 'month',
    label: 'Monthly',
    display: '₹49',
  },
  yearly: {
    price: 499,
    priceInPaise: 49900,
    currency: 'INR',
    period: 'year',
    label: 'Yearly',
    display: '₹499',
    savings: 'Save ₹89/year!',
  },
  features: [
    'Unlimited links',
    '30+ platform support',
    'Custom themes & appearance',
    'Detailed analytics dashboard',
    'SEO settings',
    'Priority support',
    'Custom OG image',
    'Remove LinkVerse branding',
    'GST invoice included',
  ],
};

// ---- Analytics date ranges ----
export const ANALYTICS_RANGES = [
  { value: '7d', label: 'Last 7 days' },
  { value: '30d', label: 'Last 30 days' },
  { value: '90d', label: 'Last 90 days' },
  { value: 'all', label: 'All Time' },
];
